load_module /usr/lib/nginx/modules/ngx_otel_module.so;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile      on;
    keepalive_timeout 65;
    access_log    /var/log/nginx/access.log;

    otel_exporter {
        endpoint alloy:4317;
    }

    otel_service_name cets-frontend-3;
    otel_trace        on;
    otel_trace_context propagate;

    include /etc/nginx/conf.d/*.conf;
}
