apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cets
  labels:
    app.kubernetes.io/part-of: cets
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx
  rules:
    - host: tickets.sky-lab.uk
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8080
          - path: /healthz
            pathType: Exact
            backend:
              service:
                name: backend
                port:
                  number: 8080
          - path: /readyz
            pathType: Exact
            backend:
              service:
                name: backend
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 8080
