apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cets
resources:
  - namespace.yaml
  - configmap.yaml
  - platform.yaml
  - minio-init-job.yaml
  - migrate-job.yaml
  - backend.yaml
  - workers.yaml
  - frontend-nginx.yaml
  - frontend.yaml
  - ingress.yaml
  - cloudflared.yaml
images:
  - name: cets-api
    newName: ghcr.io/gilbert12tw/event-ticket-system/cets-api
    newTag: 8978f375131790226b8edeac59f2311c5fc62a30
  - name: cets-frontend
    newName: ghcr.io/gilbert12tw/event-ticket-system/cets-frontend
    newTag: 8978f375131790226b8edeac59f2311c5fc62a30
