apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cets
resources:
  - namespace.yaml
  - configmap.yaml
  - platform.yaml
  - minio-init-job.yaml
  - migrate-job.yaml
  - backend.yaml
  - workers.yaml
  - frontend-nginx.yaml
  - frontend.yaml
  - ingress.yaml
  - cloudflared.yaml
images:
  - name: cets-api
    newTag: 02e30f7aafc3a9d01c372fb419544294a5d2d034
  - name: cets-frontend
    newTag: 02e30f7aafc3a9d01c372fb419544294a5d2d034
