apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cets
resources:
  - namespace.yaml
  - configmap.yaml
  - platform.yaml
  - minio-init-job.yaml
  - migrate-job.yaml
  - backend.yaml
  - workers.yaml
  - frontend-nginx.yaml
  - frontend.yaml
  - ingress.yaml
  - cloudflared.yaml
images:
  - name: cets-api
    newTag: 988d5426fd16cfed3de27921e49d8f95c07d4983
  - name: cets-frontend
    newTag: 7ec1d80a6ed1
