apiVersion: batch/v1
kind: Job
metadata:
  name: minio-init
  labels:
    app.kubernetes.io/part-of: cets
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
    argocd.argoproj.io/sync-wave: "0"
spec:
  backoffLimit: 5
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: mc
          image: minio/mc:RELEASE.2025-08-13T08-35-41Z
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: cets-app-secrets
                  key: object-storage-access-key
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cets-app-secrets
                  key: object-storage-secret-key
          command:
            - /bin/sh
            - -c
            - |
              until mc alias set local http://minio:9000 "$MINIO_ROOT_USER" "$MINIO_ROOT_PASSWORD"; do sleep 2; done
              mc mb --ignore-existing local/cets-dev
