sonar.projectKey=event-ticket-system
sonar.projectName=Corporate Event Ticketing System
sonar.host.url=${env.SONAR_HOST_URL}
sonar.token=${env.SONAR_TOKEN}
sonar.projectVersion=phase3-ha
sonar.sourceEncoding=UTF-8

sonar.sources=services/api/cmd,services/api/internal,services/api/deploy,apps/web/src,scripts,docs/openapi.yaml,docs/openapi
sonar.tests=services/api/cmd,services/api/internal,apps/web/src
sonar.test.inclusions=services/api/cmd/**/*_test.go,services/api/internal/**/*_test.go,apps/web/src/**/*.test.ts,apps/web/src/**/*.test.tsx

sonar.exclusions=**/node_modules/**,**/.turbo/**,**/.cache/**,**/coverage/**,**/dist/**,**/build/**,**/test-results/**,**/playwright-report/**,**/playwright-live-report/**,services/api/internal/httpapi/static/assets/**,services/api/internal/httpapi/static/index.html,docs/archive/**,**/*_test.go,**/*.test.ts,**/*.test.tsx
sonar.coverage.exclusions=**/*_test.go,**/*.test.ts,**/*.test.tsx,apps/web/src/test/**,services/api/internal/httpapi/static/**,services/api/deploy/**,scripts/**,docs/openapi/**

sonar.go.coverage.reportPaths=services/api/coverage.sonar.out
sonar.javascript.lcov.reportPaths=apps/web/coverage/lcov.info
