export const employees = [
  {
    employee_id: "E1001",
    full_name: "Ariel Chen",
    department: "Engineering",
    site: "Taipei HQ",
    job_grade: 6,
    employment_status: "active",
  },
  {
    employee_id: "E1002",
    full_name: "Ben Lin",
    department: "Engineering",
    site: "Taipei HQ",
    job_grade: 5,
    employment_status: "active",
  },
  {
    employee_id: "E1003",
    full_name: "Tina Chang",
    department: "Engineering",
    site: "Taipei HQ",
    job_grade: 5,
    employment_status: "active",
  },
  {
    employee_id: "E2001",
    full_name: "Carla Wu",
    department: "Sales",
    site: "Taipei HQ",
    job_grade: 4,
    employment_status: "active",
  },
  {
    employee_id: "E1004",
    full_name: "David Tan",
    department: "Engineering",
    site: "Taipei HQ",
    job_grade: 5,
    employment_status: "active",
  },
  {
    employee_id: "E1005",
    full_name: "Emily Liu",
    department: "Engineering",
    site: "Taipei HQ",
    job_grade: 6,
    employment_status: "active",
  },
  {
    employee_id: "E1006",
    full_name: "Frank Wang",
    department: "Engineering",
    site: "Taipei HQ",
    job_grade: 5,
    employment_status: "active",
  },
  {
    employee_id: "E1007",
    full_name: "Grace Huang",
    department: "Engineering",
    site: "Taipei HQ",
    job_grade: 5,
    employment_status: "active",
  },
  {
    employee_id: "E1008",
    full_name: "Henry Cheng",
    department: "Engineering",
    site: "Taipei HQ",
    job_grade: 5,
    employment_status: "active",
  },
  {
    employee_id: "E1009",
    full_name: "Iris Yang",
    department: "Engineering",
    site: "Taipei HQ",
    job_grade: 6,
    employment_status: "active",
  },
  {
    employee_id: "E1010",
    full_name: "Jack Kao",
    department: "Engineering",
    site: "Taipei HQ",
    job_grade: 5,
    employment_status: "active",
  },
  {
    employee_id: "E3001",
    full_name: "Tainan User",
    department: "Engineering",
    site: "Tainan HQ",
    job_grade: 5,
    employment_status: "active",
  },
];
