apiVersion: 1

datasources:
  - name: Prometheus
    uid: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
  - name: Loki
    uid: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      derivedFields:
        - name: Tempo trace
          matcherRegex: '"otel_trace_id":"([a-f0-9]{32})"'
          datasourceUid: Tempo
          url: "$${__value.raw}"
          urlDisplayLabel: "Open trace"
    editable: false
  - name: Tempo
    uid: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: false
  - name: Pyroscope
    uid: Pyroscope
    type: grafana-pyroscope-datasource
    access: proxy
    url: http://pyroscope:4040
    editable: false
