apiVersion: 1

datasources:
  - name: Prometheus
    uid: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
  - name: Loki
    uid: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: false
    jsonData:
      derivedFields:
        - datasourceUid: Tempo
          matcherRegex: "\\\"otel_trace_id\\\":\\\"([a-fA-F0-9]{32})\\\""
          name: otel_trace_id
          url: "$${__value.raw}"
  - name: Tempo
    uid: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: false
    jsonData:
      serviceMap:
        datasourceUid: Prometheus
      nodeGraph:
        enabled: true
      tracesToLogsV2:
        datasourceUid: Loki
        filterByTraceID: true
        spanStartTimeShift: "-5m"
        spanEndTimeShift: "5m"
      tracesToMetrics:
        datasourceUid: Prometheus
        queries:
          - name: "Span request rate"
            query: "sum(rate(traces_spanmetrics_calls_total{$$__tags}[5m]))"
          - name: "Span p99 latency"
            query: "histogram_quantile(0.99, sum by (le) (rate(traces_spanmetrics_duration_seconds_bucket{$$__tags}[5m])))"
      tracesToProfiles:
        datasourceUid: Pyroscope
        profileTypeId: "process_cpu:cpu:nanoseconds:cpu:nanoseconds"
        tags: ["service.name", "deployment.environment", "service.version"]
  - name: Pyroscope
    uid: Pyroscope
    type: grafana-pyroscope-datasource
    access: proxy
    url: http://pyroscope:4040
    editable: false
