#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
# shellcheck source=lib.sh
. "$SCRIPT_DIR/lib.sh"

load_env

generate_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32
  else
    tr -dc 'A-Za-z0-9' </dev/urandom | head -c 64
  fi
}

if [ -f "$LOCAL_ENV" ] && [ "${OVERWRITE:-false}" != "true" ]; then
  die "$LOCAL_ENV already exists; set OVERWRITE=true only if you intentionally want to regenerate it"
fi

require_env BAREMETAL_BECOME_PASSWORD

umask 077
cat >"$LOCAL_ENV" <<EOF
BAREMETAL_SSH_USER=${BAREMETAL_SSH_USER}
BAREMETAL_BECOME_PASSWORD='${BAREMETAL_BECOME_PASSWORD}'

BAREMETAL_NODE_1=${BAREMETAL_NODE_1}
BAREMETAL_NODE_1_IP=${BAREMETAL_NODE_1_IP}
BAREMETAL_NODE_2=${BAREMETAL_NODE_2}
BAREMETAL_NODE_2_IP=${BAREMETAL_NODE_2_IP}
BAREMETAL_NODE_3=${BAREMETAL_NODE_3}
BAREMETAL_NODE_3_IP=${BAREMETAL_NODE_3_IP}

K8S_VERSION=${K8S_VERSION}
CONTAINERD_IO_VERSION=${CONTAINERD_IO_VERSION}
K8S_POD_CIDR=${K8S_POD_CIDR}
K8S_SERVICE_CIDR=${K8S_SERVICE_CIDR}
K8S_API_VIP=${K8S_API_VIP}
K8S_API_PORT=${K8S_API_PORT}
K8S_INTERFACE=${K8S_INTERFACE}

METALLB_LB_POOL=${METALLB_LB_POOL}
METALLB_INGRESS_IP=${METALLB_INGRESS_IP}
METALLB_PEER_ADDRESS=${METALLB_PEER_ADDRESS}
METALLB_MY_ASN=${METALLB_MY_ASN}
METALLB_PEER_ASN=${METALLB_PEER_ASN}
METALLB_BGP_HOLD_TIME=${METALLB_BGP_HOLD_TIME}

CETS_NAMESPACE=${CETS_NAMESPACE}
CETS_API_IMAGE=${CETS_API_IMAGE:-}
CETS_FRONTEND_IMAGE=${CETS_FRONTEND_IMAGE:-}
CETS_IMAGE_PULL_SECRET=${CETS_IMAGE_PULL_SECRET:-}
CETS_PUBLIC_HOSTNAME=${CETS_PUBLIC_HOSTNAME}

POSTGRES_DB=${POSTGRES_DB:-cets}
POSTGRES_USER=${POSTGRES_USER:-cets}
POSTGRES_PASSWORD=$(generate_secret)
TOKEN_SIGNING_SECRET=$(generate_secret)
PROVIDER_TOKEN_SECRET=$(generate_secret)
BOOKING_RESERVATION_HASH_SECRET=$(generate_secret)
OBJECT_STORAGE_BUCKET=${OBJECT_STORAGE_BUCKET:-cets-dev}
OBJECT_STORAGE_ACCESS_KEY=${OBJECT_STORAGE_ACCESS_KEY:-minioadmin}
OBJECT_STORAGE_SECRET_KEY=$(generate_secret)
MAILER_FROM=${MAILER_FROM:-no-reply@cets.local}
MAILER_REDIRECT_TO=${MAILER_REDIRECT_TO:-}

CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN:-}
CLOUDFLARE_ACCOUNT_ID=${CLOUDFLARE_ACCOUNT_ID:-}
CLOUDFLARE_ZONE_ID=${CLOUDFLARE_ZONE_ID:-}
CLOUDFLARE_ZONE_NAME=${CLOUDFLARE_ZONE_NAME:-example.com}
CLOUDFLARE_TUNNEL_NAME=${CLOUDFLARE_TUNNEL_NAME}
CLOUDFLARE_ACCESS_ALLOWED_EMAILS=${CLOUDFLARE_ACCESS_ALLOWED_EMAILS:-}
CLOUDFLARE_ACCESS_DEVICE_POSTURE_RULE_IDS=${CLOUDFLARE_ACCESS_DEVICE_POSTURE_RULE_IDS:-}
EOF

log "wrote $LOCAL_ENV with generated local app secrets"
log "fill CETS_* image values and CLOUDFLARE_* values before Cloudflare/app apply"
