package deploy

const (
	composeFile              = "compose.yaml"
	composePhase3HAFile      = "compose.phase3-ha.yaml"
	composeWorkerIsolation   = "compose.worker-isolation.yaml"
	envExampleFile           = ".env.example"
	githubCIWorkflowFile     = "../../../.github/workflows/ci.yml"
	kubectlLogFile           = "kubectl.log"
	phase3CapacityScript     = "phase3-capacity.sh"
	phase3CapacityReport     = "phase3-capacity-report.sh"
	phase3CapacityEvidence   = "phase3-capacity-correctness-evidence.sh"
	phase3CapacityPreflight  = "phase3-capacity-preflight.sh"
	phase3HeaderReplicasAwk  = "phase3-header-replicas.awk"
	phase3ReplicaSpreadAwk   = "phase3-replica-spread-check.awk"
	phase3RunReport          = "run-report.md"
	phase3SonarResultScript  = "phase3-sonar-result.sh"
	phase3VerifyScript       = "phase3-verify.sh"
	phase3VerifyPrometheus   = "phase3-verify-prometheus-evidence.sh"
	phase3VerifyLoki         = "phase3-verify-loki-evidence.sh"
	postgresFailoverScript   = "71-verify-postgres-failover.sh"
	failureDrillScript       = "70-failure-drill.sh"
	qualityReportFile        = "quality-report.md"
	sonarResultReportFile    = "sonar-result.md"
	sonarTaskFile            = "report-task.txt"
	k6SummaryFile            = "k6.json"
	sonarHostLocalEnv        = "SONAR_HOST_URL=http://sonar.local"
	sonarTokenValue          = "phase3-secret-token"
	sonarTokenEnv            = "SONAR_TOKEN=" + sonarTokenValue
	sonarRequiredMessage     = "SONAR_HOST_URL is required"
	sonarCommandTrueEnv      = "CETS_PHASE3_SONAR_COMMAND=true"
	sonarResultReportEnv     = "CETS_PHASE3_SONAR_RESULT_REPORT="
	sonarTaskFileEnv         = "CETS_PHASE3_SONAR_TASK_FILE="
	sonarWaitDisabledEnv     = "CETS_PHASE3_SONAR_WAIT_SECONDS=0"
	qualityReportEnv         = "CETS_PHASE3_QUALITY_REPORT="
	phase3ArtifactDirEnv     = "CETS_PHASE3_RUN_ARTIFACT_DIR="
	phase3RunReportEnv       = "CETS_PHASE3_RUN_REPORT="
	baremetalDrillArtifact   = "BAREMETAL_DRILL_ARTIFACT_DIR="
	baremetalPGArtifact      = "BAREMETAL_PG_FAILOVER_ARTIFACT_DIR="
	baremetalPGSmokeScript   = "BAREMETAL_PG_FAILOVER_SMOKE_SCRIPT="
	targetNodeWork2Env       = "TARGET_NODE=work2"
	fakeKubectlLogEnv        = "FAKE_KUBECTL_LOG="
	postgresDBEnv            = "POSTGRES_DB=cets"
	postgresUserEnv          = "POSTGRES_USER=cets"
	statusBlockedRow         = "| Status | `blocked` |"
	statusFailedRow          = "| Status | `failed` |"
	exitCodeOneRow           = "| Exit code | `1` |"
	markdownFieldHeader      = "| Field | Value |"
	markdownSeparator        = "| --- | --- |"
	oldPrimaryPostgresOneRow = "| Old primary | `cets-postgres-1` |"
	oldPrimaryDetectedEvent  = "cets-postgres-1|old_primary_detected"
	deletePostgresOnePod     = "delete pod cets-postgres-1"
	drillFailedEvent         = "drill|failed"
	cordonWork2Command       = "cordon work2"
	drainWork2Command        = "drain work2"
	mainFunctionFragment     = "main() {"
	missingPhase3ScriptError = "required Phase 3 script is missing or not executable"
	runLogRowPrefix          = "| Run log | `"
)
