apiVersion: batch/v1
kind: Job
metadata:
  name: cets-migrate
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app.kubernetes.io/part-of: cets
spec:
  ttlSecondsAfterFinished: 600
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: cets-migrate
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: cets-api:v0.0.1
          imagePullPolicy: IfNotPresent
          args: ["migrate"]
          envFrom:
            - configMapRef:
                name: cets-config
            - secretRef:
                name: cets-runtime-env
