FROM alpine:3.21
RUN wget -qO /etc/apk/keys/nginx_signing.rsa.pub https://nginx.org/keys/nginx_signing.rsa.pub \
    && echo "https://nginx.org/packages/mainline/alpine/v3.21/main" >> /etc/apk/repositories \
    && apk add --no-cache nginx nginx-module-otel \
    && rm -rf /var/cache/apk/*
EXPOSE 8080
STOPSIGNAL SIGQUIT
CMD ["nginx", "-g", "daemon off;"]
