apiVersion: v1
kind: ConfigMap
metadata:
  name: cets-prometheus-kubernetes-scrape-example
  namespace: cets-observability
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: cets-observability-reference
data:
  prometheus-kubernetes-scrape.yml: |
    scrape_configs:
      - job_name: cets-kube-state-metrics
        honor_labels: true
        static_configs:
          - targets:
              - kube-state-metrics.cets-observability.svc:8080
            labels:
              signal_scope: orchestration-state
              service: kube-state-metrics
